export const authConstants = {
  FETCH_USER: 'FETCH_USER',
  AUTHORIZED_USER: 'AUTHORIZED_USER',
  UNAUTHORIZED_USER: 'UNAUTHORIZED_USER',
  AUTH_ERROR: 'AUTH_ERROR',
  SIGNUP_USER: 'SIGNUP_USER',
  USER_TOKEN: 'USER_TOKEN'
};
